describe('Auth, check some buttons and fields', () => {
    it('Auth, check some buttons and fields', () => {
        cy.visit('https://izibet.tn/games')
        cy.viewport(1920, 1080)

        cy.get('#icon-button-navbar-button-open-profile-login')
            .click()
        cy.get('#input_username')
            .type('player')
        cy.get('#input_password')
            .type('player')
        cy.get('#button-sing-in-modal')
            .click()
            .wait(2000)

        cy.get('#icon-button-navbar-button-open-profile-login')
            .click()
        cy.get('#button-profile_modal_log_out')
            .click()
            .wait(3000)

        cy.get('.sc-IIEeM > :nth-child(3)')
            .click()
            /*.wait(3000)*/
        cy.scrollTo(0, 1000)
        cy.get('#button-accrodion-start')
            .click()
            .wait(1500)
        cy.get('.sc-IIEeM > :nth-child(4)')
            .click()
            .wait(1500)
        cy.get('.sc-IIEeM > :nth-child(2)')
            .click()
            .wait(20000)


        cy.get('#icon-button-navbar-button-open-profile-login')
            .click()
        cy.get('#input_username')
            .type('player')
        cy.get('#input_password')
            .type('player')
        cy.get('#button-sing-in-modal')
            .click()
            .wait(2000)

        cy.get('.sc-IIEeM > :nth-child(3)')
            .click()
            .wait(4000)
        cy.get('.sc-bhVIhj > :nth-child(1) > .sc-ftvSup > .sc-ksZaOG > #button-play-game-5_lions_megaways')
            .click()
            .wait(20000)
        cy.get('[style="cursor: pointer;"]')
            .click()

        cy.get('#button-filter-favorite-1')
            .click()
            .wait(2000)
        cy.get('#button-filter-all-0')
            .click()
            .wait(2000)
        cy.scrollTo(0, 500)
        cy.get('#icon-button-wolf_moon > svg > g > path')
            .click()
        cy.get('#icon-button-wild_dragon > svg > g > path')
            .click()
        cy.get('#icon-button-hot_hot_fruit > svg > g > path')
            .click()
        cy.get('#icon-button-sweet_bonanza > svg > g > path')
            .click()
        cy.get('#button-filter-all-0')
            .click()
            .wait(2000)
        cy.get('#button-filter-favorite-1')
            .click()
            .wait(2000)
        cy.get('#icon-button-wolf_moon > svg > g > path')
            .click()
        cy.get('#icon-button-wild_dragon > svg > g > path')
            .click()
        cy.get('#icon-button-hot_hot_fruit > svg > g > path')
            .click()
        cy.get('#icon-button-sweet_bonanza > svg > g > path')
            .click()
        cy.get('#button-filter-all-0')
            .click()
            .wait(2000)
        cy.get('#button-filter-favorite-1')
            .click()
            .wait(4000)

        cy.get('#button-filter-all-0')
            .click()
            .wait(2000)
        cy.get('#button-accordion-amatic > .sc-bPyhqo')
            .click()
        cy.get('#button-play-game-a_book_of_aztec')
            .click()
    })
})